apiVersion: v1
kind: Service
metadata:
  name: app-ml-service
spec:
  type: NodePort
  selector:
    app: app-ml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080

