apiVersion: v1
kind: Pod
metadata:
  name: minio
  labels:
    app: minio
spec:
  containers:
    - name: minio
      image: quay.io/minio/minio
      args:
        - server
        - /data
        - --console-address
        - ":9001"
      ports:
        - containerPort: 9000
        - containerPort: 9001
      env:
        - name: MINIO_ROOT_USER
          value: minioadmin
        - name: MINIO_ROOT_PASSWORD
          value: minioadmin
